CREATE TABLE "AUTH_GROUP" (
  "AUTH_GROUP_NAME" VARCHAR(35)  NOT NULL PRIMARY KEY,
  "DESCRIPTION"     VARCHAR(355) NOT NULL,
  "CREATED_AT"      BIGINT       NOT NULL,
  "UPDATED_AT"      BIGINT       NOT NULL
);
CREATE TABLE "AUTH_GROUP_ROLE" (
  "AUTH_GROUP_ROLE_ID" SERIAL      NOT NULL PRIMARY KEY,
  "AUTH_ROLE_NAME"     VARCHAR(25) NOT NULL,
  "AUTH_GROUP_NAME"    VARCHAR(35) NOT NULL,
  "CREATED_AT"         BIGINT      NOT NULL,
  "UPDATED_AT"         BIGINT      NOT NULL
);
CREATE TABLE "AUTH_ROLE" (
  "AUTH_ROLE_NAME" VARCHAR(25)  NOT NULL PRIMARY KEY,
  "DESCRIPTION"    VARCHAR(355) NOT NULL,
  "CREATED_AT"     BIGINT       NOT NULL,
  "UPDATED_AT"     BIGINT       NOT NULL
);
CREATE INDEX "DESCRIPTION_IDX" ON "AUTH_ROLE" ("DESCRIPTION");
CREATE TABLE "PROPERTY" (
  "PROPERTY_KEY" VARCHAR(255)  NOT NULL PRIMARY KEY,
  "VALUE"        VARCHAR(1255) NOT NULL
);
CREATE TABLE "USER" (
  "USER_ID"         SERIAL       NOT NULL PRIMARY KEY,
  "USERNAME"        VARCHAR(35)  NOT NULL,
  "PASSWORD"        VARCHAR(555) NOT NULL,
  "ENABLED"         BOOLEAN      NOT NULL,
  "ACTIVATION_CODE" VARCHAR(555) NOT NULL,
  "NAME"            VARCHAR(255) NOT NULL,
  "EMAIL"           VARCHAR(55)  NOT NULL,
  "PHONE"           VARCHAR(16),
  "PHOTO"           TEXT,
  "ADDRESS"         VARCHAR(555),
  "CITY"            VARCHAR(55),
  "POSTAL_CODE"     VARCHAR(35),
  "DATE_OF_BIRTH"   BIGINT,
  "AUTH_GROUP_NAME" VARCHAR(35)  NOT NULL,
  "REMEMBER_TOKEN"  VARCHAR(555),
  "CREATED_AT"      BIGINT       NOT NULL,
  "UPDATE_AT"       BIGINT       NOT NULL
);
CREATE UNIQUE INDEX "EMAIL_UNIQUE" ON "USER" ("EMAIL");
CREATE UNIQUE INDEX "USERNAME_UNIQUE" ON "USER" ("USERNAME");
ALTER TABLE "AUTH_GROUP_ROLE" ADD CONSTRAINT "group_group_role_fk" FOREIGN KEY ("AUTH_GROUP_NAME") REFERENCES "AUTH_GROUP" ("AUTH_GROUP_NAME") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "AUTH_GROUP_ROLE" ADD CONSTRAINT "role_group_role_fk" FOREIGN KEY ("AUTH_ROLE_NAME") REFERENCES "AUTH_ROLE" ("AUTH_ROLE_NAME") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "USER" ADD CONSTRAINT "group_user_fk" FOREIGN KEY ("AUTH_GROUP_NAME") REFERENCES "AUTH_GROUP" ("AUTH_GROUP_NAME") ON UPDATE CASCADE ON DELETE RESTRICT;
